#!/bin/bash

# Function : 使用except无需输入密码自动登录ssh
# Author   : Jiangxianli
# Date     : 2016/01/14
# Github   : https://github.com/jiangxianli/SSHAutoLogin

#默认服务器配置项
#格式："服务器名称 端口号 IP地址 登录用户名 登录密码"
CONFIGS=(
    "Server0 22 220.181.57.217 root baidu.com"
    "Server1 22 66.102.251.33 root sina.com"
)

#读取自定义服务器配置文件（server_config）列表，合并服务器配置列表
if [ -f server_config ]; then
	while read line
	do
		CONFIGS+=("$line")
	done < server_config
fi

#服务器配置数
CONFIG_LENGTH=${#CONFIGS[*]}  #配置站点个数

if [[ $CONFIG_LENGTH -le 0 ]] ;
then
    echo "Sorry, there aren't any configured server!"
    echo "Please add configuration following the rules above!"
    exit ;
fi

#服务器配置菜单
function ConfigList(){
    for ((i=0;i<${CONFIG_LENGTH};i++));  
    do  
        CONFIG=(${CONFIGS[$i]}) #将一维sites字符串赋值到数组  
        serverNum=$(($i+1)) 
        echo "(${serverNum})--${CONFIG[0]}(${CONFIG[2]})"
    done 
}

#登录菜单
function LoginMenu(){
    if [ "$1" == "" ]; then
        AutoLogin $1
    else
        echo "Choose server from list below:"
        ConfigList
        echo "Please input the server order "
    fi
}

#选择登录的服务器
function ChooseServer(){
    read serverNum
    if [[ $serverNum -gt $CONFIG_LENGTH ]] ;
    then
        echo "Wrong order, please try again:"
        ChooseServer ;
        return ;
    fi
    if [[ $serverNum -lt 1 ]] ;
    then
        echo "Wrong order, please try again:"
        ChooseServer ;
        return ;
    fi
 
    AutoLogin $serverNum;
}  

#自动登录
function AutoLogin(){
    
    num=$(($1-1)) 
    CONFIG=(${CONFIGS[$num]})  
    echo "Logging into【${CONFIG[0]}】"
    expect -c "
        spawn ssh -p ${CONFIG[1]} ${CONFIG[3]}@${CONFIG[2]}
        expect {
            \"*assword\" {set timeout 6000; send \"${CONFIG[4]}\n\"; exp_continue ; sleep 3; }
            \"yes/no\" {send \"yes\n\"; exp_continue;}
            \"Last*\" {  send_user \"\nsucceed【${CONFIG[0]}】\n\";}
        }
       
   interact"
   echo "Already exit【${CONFIG[0]}】"
    
}

# 程序入口
if [ 1 == $# ]; then
    if [ 'list' == $1 ]; then
        ConfigList
    else
        AutoLogin $1
    fi
else
    LoginMenu 
    ChooseServer 
fi
